### ISSUE TITLE
你好问下 论文的补充材料链接有吗

### ISSUE THREAD

**Issue by qqyqq666** [ShenZheng2000/PointNorm-for-Point-Cloud-Analysis#3]
你好问下 论文的补充材料链接有吗

**Comment by ShenZheng2000** [comment]
最新版本的[arxiv](https://arxiv.org/pdf/2207.06324.pdf)，已经把补充材料整合入正文了。

**Comment by qqyqq666** [comment]
LocalGrouper模块 是PointMLP中的几何仿射模块吗

**Comment by ShenZheng2000** [comment]
代码参照的模板，是PointMLP的几何仿射模块。里面的操作，换成了Point Norm (PN)，和Reverse Point Norm (RPN)。

**Comment by qqyqq666** [comment]
好的 十分感谢
