### ISSUE TITLE
关于 C-ResBlock模块

### ISSUE THREAD

**Issue by xiaobaitu123344** [ShenZheng2000/PointNorm-for-Point-Cloud-Analysis#4]
请问您的这个C-ResBlock模块对应的是代码里的那部分？谢谢

**Comment by ShenZheng2000** [comment]
这个版本的代码，和最新的[arxiv](https://arxiv.org/pdf/2207.06324.pdf)里面，我们只用了基础的ResBlock。

以ScanObjectNN的实验为例子，ResBlock对应的class，是[PreExtraction](https://github.com/ShenZheng2000/PointNorm-for-Point-Cloud-Analysis/blob/main/classification_ScanObjectNN/models/PointNorm.py#L355)和[PosExtraction](https://github.com/ShenZheng2000/PointNorm-for-Point-Cloud-Analysis/blob/main/classification_ScanObjectNN/models/PointNorm.py#L391)

**Comment by xiaobaitu123344** [comment]
哪您们提出的C-ResBlock在那篇论文里可以找到，或者是否可以跟新一下代码，谢谢

**Comment by xiaobaitu123344** [comment]
我对您们提出的这个C-ResBlock很感兴趣

**Comment by ShenZheng2000** [comment]
以[PreExtraction](https://github.com/ShenZheng2000/PointNorm-for-Point-Cloud-Analysis/blob/main/classification_ScanObjectNN/models/PointNorm.py#L367)函数为例。

可以对for loop做以下修改，从而在res_expansion<=1.0的时候，用ResBlock with bottleneck design。在res_expansion>1.0的时候，使用理论上更高速并且省时的Inverted ResBlock。

```
for _ in range(blocks):
    if use_inv_res:
        operation.append(
            InvertedResidual(out_channels, out_channels, expand_ratio=res_expansion)
        )
    else:
        if res_expansion > 1.0: # switch to Inverted ResBlock
            operation.append(
                InvertedResidual(out_channels, out_channels, expand_ratio=res_expansion)
        )
        else: # stay with ResBlock
            operation.append(
                ConvBNReLURes1D(out_channels, groups=groups, res_expansion=res_expansion,
                                bias=bias, activation=activation)
            )
self.operation = nn.Sequential(*operation)
```

在实验中，我们发现，res_expansion >1.0的情况下，无论是纯ResBlock，纯InvResBlock，还是C-ResBlock，都无法超越res_expansion=1.0时的指标。

我们推测有两种原因。

第一种可能。C-ResBlock的一部分，是基于我写的[Inverted ResBlock](https://github.com/ShenZheng2000/PointNorm-for-Point-Cloud-Analysis/blob/main/classification_ScanObjectNN/models/PointNorm.py#L322)。这个类，是我从2D版本的Inverted ResBlock直接迁移过来的，可能不适用3D的点云。

第二种可能。我的训练数据规模都不大。模型换了更大的res_expansion之后，参数量增加了，过拟合更严重，最终的测试精度反而降低。

因此，在现在版本的论文中，我们最终选择放弃C-ResBlock这个小的improvement，而是花更多的实验和分析，去更全面地论证DualNorm这个核心创新点的优势。

**Comment by xiaobaitu123344** [comment]
十分感谢作者的耐心解答，再次十分感谢，受益匪浅
