### ISSUE TITLE
Visualization issues

### ISSUE THREAD

**Issue by qqyqq666** [ShenZheng2000/PointNorm-for-Point-Cloud-Analysis#7]
If I visualize other components, how should I adjust the angle and select the ID number

**Comment by ShenZheng2000** [comment]
Could you please provide more specific details? For example, which script are you using, and which dataset are you trying to visualize?

**Comment by qqyqq666** [comment]
I want to visualize the shapenetcore_ Partano_ Segmentation_ Benchmark_ V0_ Normal other components, but I don't know how to adjust the angle and select the ID

**Comment by ShenZheng2000** [comment]
The readme states that visualizing part segmentation results can be done with the following code block:
```
python plot_ptseg.py --model {PointNorm/PointNormTiny} --exp_name {your_checkpoint_name} --angle_one {your_elevation_angle} --angle_two {your_azimuth_angle} --id {the_object_id}
```

Besides, some examples were provided as well to help you reproduce the result in the paper.
```
python plot_ptseg.py --model PointNorm --exp_name PointNorm_7_8_v1 --angle_one 330 --angle_two 90 --id 1 # airplane
python plot_ptseg.py --model PointNorm --exp_name PointNorm_7_8_v1 -angle_one 270 --angle_two 90 --id 500 # car
python plot_ptseg.py --model PointNorm --exp_name PointNorm_7_8_v1 --angle_one 120 --angle_two 270 --id 1000 # chair
python plot_ptseg.py --model PointNorm --exp_name PointNorm_7_8_v1 --angle_one 90 --angle_two 270 --id 1500 # lamp
python plot_ptseg.py --model PointNorm --exp_name PointNorm_7_8_v1 --angle_one 90 --angle_two 270 --id 2000 # skateboard
```

Regarding your question:

(1) You can pick any angle_one (elevation angle) and angle_two (azimuth angle) to obtain a 2D screenshot from a 3D point cloud.

(2) I do not quite remember the specific IDs for each object, but they should be similar to this: airplane (1-499), car (500-999), chair (1000-1499), lamp (1500-1999), skateboard (2000-2499).

**Comment by qqyqq666** [comment]
Okay, thank you very much
&nbsp;


许多年以后
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月9日(星期二) 凌晨4:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ShenZheng2000/PointNorm-for-Point-Cloud-Analysis] Visualization issues (Issue #7)





 
The readme states that visualizing part segmentation results can be done with the following code block:
 python plot_ptseg.py --model {PointNorm/PointNormTiny} --exp_name {your_checkpoint_name} --angle_one {your_elevation_angle} --angle_two {your_azimuth_angle} --id {the_object_id}  
Besides, some examples were provided as well to help you reproduce the result in the paper.
 python plot_ptseg.py --model PointNorm --exp_name PointNorm_7_8_v1 --angle_one 330 --angle_two 90 --id 1 # airplane python plot_ptseg.py --model PointNorm --exp_name PointNorm_7_8_v1 -angle_one 270 --angle_two 90 --id 500 # car python plot_ptseg.py --model PointNorm --exp_name PointNorm_7_8_v1 --angle_one 120 --angle_two 270 --id 1000 # chair python plot_ptseg.py --model PointNorm --exp_name PointNorm_7_8_v1 --angle_one 90 --angle_two 270 --id 1500 # lamp python plot_ptseg.py --model PointNorm --exp_name PointNorm_7_8_v1 --angle_one 90 --angle_two 270 --id 2000 # skateboard  
Regarding your question:
 
(1) You can pick any angle_one (elevation angle) and angle_two (azimuth) to obtain a 2D screenshot from a 3D point cloud.
 
(2) I do not quite remember the specific IDs for each object, but they should be similar to this: airplane (1-499), car (500-999), chair (1000-1499), lamp (1500-1999), skateboard (2000-2499).
